### PR TITLE
(Maybe) Fixes #2

### LINKED ISSUE #2: IRC to small to do CAPTCHA
When it asks for a CAPTCHA, there isn't the space to do it. It is impossible.

### PR DESCRIPTION
**Pull request by brmbrmcar**

### CODE REVIEW

**Comment by maxteufel** [comment]
Please amend this commit and provide a more detailed description in the commit message.

Furthermore, changes to the website should be submitted to the [SuperTux/htdocs](https://github.com/SuperTux/htdocs) repository which is then compiled to the HTML files. And - don't open a pull request unless you know it actually fixes something or adds a new feature.

**Comment by brmbrmcar** [comment]
It isn't supported in HTML5.

**Comment by brmbrmcar** [comment]
I cannot check it. Someone else needs to.

**Comment by maxteufel** [comment]
Please move this to the new repository if this still applies.

**Pull request closed without merging**
