### PR TITLE
Use XSLT for new website

### PR DESCRIPTION
**Pull request by o11c**
This PR converts the new website design to use XSLT transforms to create the content on the client, which is much more maintainable. Particularly, each file is shorter and has a more specific purpose, and it is harder to write incorrect code. Additionally, this will make it easier for the browser to cache it.
- Generates well-formed XHTML.
- Automatic screenshot, news, and download extraction.
- Automatically use the header/footer on every page.
- Tested in XSLTproc, Firefox, and Chromium (note that Chrome requires an http server; WebKit has bugs with `file://` URLs)
- Compatible with Internet Explorer
- Brief message if XSLT is not supported (currently only on main page to avoid copypasta)

### CODE REVIEW

**Comment by Grumbel** [comment]
The webpage is already generated from XML/XSLT, see `https://github.com/SuperTux/htdocs`, `SuperTux.github.io` is just dumb storage for the generated files. Don't see much point in moving the generation online, as that just breaks compatibility all over the place.

**Comment by sydneyjd** [comment]
@Grumbel The website that i just built does not use htdocs. I build it from scratch and pushed it to the repos. http://supertux.github.io/newwebsite/ We are hoping to replace supertux.github.io with it after we get all the look issues solved.
That is what o11c is referencing to IIRC.
Also we are working on getting supertux.lethargik.org to redirect to supertux.github.io, so people can manually edit the html and just push the changes to get merged by the devs.

**Comment by o11c** [comment]
@Grumbel What concrete systems don't support client-side XSLT these days? A lot has changed since 2003.

Minimizing the number of steps in a process is best. If nothing else, if @sydneyjd had been aware that the files were generated, he would not have tried to make changes in html form.

If precalculated XSLT is the way to go, perhaps htdocs should have a travis upload hook, and certainly there should be an obvious file saying "this repo is automatically generated, do not edit".

The htdocs repo definitely gives better pages than what @sydneyjd made, but he is right about the need for new content like his.

**Comment by sydneyjd** [comment]
I really don't care what is done, just as long as my work doesn't go to waste.

**Comment by Grumbel** [comment]
I merged:

https://github.com/o11c/SuperTux.github.io

into the `htdocs` repository, `develop` branch:

https://github.com/SuperTux/htdocs/tree/develop

Going to add Makefile and stuff for offline generation.

**Pull request closed without merging**
